// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqdl7UN1-j_TgqyMeFvPrNOISM_KQW5SM',
    appId: '1:91018791595:web:424d22be156003926785ee',
    messagingSenderId: '91018791595',
    projectId: 'user-crud-b23f7',
    authDomain: 'user-crud-b23f7.firebaseapp.com',
    storageBucket: 'user-crud-b23f7.appspot.com',
    measurementId: 'G-Z5GZZTP0NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChhouXoe7zd0avFficsIYe7PVkDWL6LVc',
    appId: '1:91018791595:android:c01b77ac4ff6ffe56785ee',
    messagingSenderId: '91018791595',
    projectId: 'user-crud-b23f7',
    storageBucket: 'user-crud-b23f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcqgVHzpQe4IbAQNS5-Hve_WodrNSKbU',
    appId: '1:91018791595:ios:6b22380a7b986dd56785ee',
    messagingSenderId: '91018791595',
    projectId: 'user-crud-b23f7',
    storageBucket: 'user-crud-b23f7.appspot.com',
    iosBundleId: 'com.example.userCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcqgVHzpQe4IbAQNS5-Hve_WodrNSKbU',
    appId: '1:91018791595:ios:6b22380a7b986dd56785ee',
    messagingSenderId: '91018791595',
    projectId: 'user-crud-b23f7',
    storageBucket: 'user-crud-b23f7.appspot.com',
    iosBundleId: 'com.example.userCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqdl7UN1-j_TgqyMeFvPrNOISM_KQW5SM',
    appId: '1:91018791595:web:e7122926ab1b55e46785ee',
    messagingSenderId: '91018791595',
    projectId: 'user-crud-b23f7',
    authDomain: 'user-crud-b23f7.firebaseapp.com',
    storageBucket: 'user-crud-b23f7.appspot.com',
    measurementId: 'G-HSGF07H2SV',
  );
}
